#!/usr/bin/env python3
"""Generate the US Economic State Analysis document."""
from __future__ import annotations
import argparse, json, os, sys, time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Optional
import httpx

FRED_API_KEY = os.environ.get("FRED_API_KEY")
EIA_API_KEY = os.environ.get("EIA_API_KEY")

PRIORITY_SERIES = {
    "economic": ["GDPC1"], "inflation": ["CPIAUCSL", "PCEPILFE"],
    "employment": ["UNRATE", "PAYEMS"], "housing": ["MSPUS", "MORTGAGE30US"],
    "consumer": ["UMCSENT", "PSAVERT"], "financial": ["FEDFUNDS", "DGS10", "DGS2"],
}

def fetch_series(series_id: str, years: int = 10) -> Optional[dict]:
    if not FRED_API_KEY: return None
    end = datetime.now(timezone.utc)
    start = end - timedelta(days=years * 365)
    url = f"https://api.stlouisfed.org/fred/series/observations?series_id={series_id}&api_key={FRED_API_KEY}&file_type=json&observation_start={start.strftime('%Y-%m-%d')}&observation_end={end.strftime('%Y-%m-%d')}"
    try:
        resp = httpx.get(url, timeout=30)
        if resp.status_code != 200: return None
        data = resp.json()
        obs = [{"date": o["date"], "value": float(o["value"])} for o in data.get("observations", []) if o["value"] != "."]
        if not obs: return None
        return {"id": series_id, "name": series_id, "observations": obs, "latest": obs[-1] if obs else None}
    except Exception: return None

def generate_markdown(results: dict, gas_price=None) -> str:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S")
    md = f"# US Economic State Analysis\n\n**Generated:** {now}\n**Sources:** FRED, EIA\n\n---\n\n## Executive Summary\n\n"
    unrate = results.get("UNRATE")
    if unrate and unrate["latest"]: md += f"- **Unemployment** at {unrate['latest']['value']:.1f}%\n"
    fedfunds = results.get("FEDFUNDS")
    if fedfunds and fedfunds["latest"]: md += f"- **Fed Funds Rate** at {fedfunds['latest']['value']:.2f}%\n"
    md += "\n---\n\n*Analysis generated by US-Metrics skill*\n"
    return md

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output")
    args = parser.parse_args()
    if not FRED_API_KEY: print("FRED_API_KEY not set", file=sys.stderr); sys.exit(1)
    print("Fetching data from FRED API...", file=sys.stderr)
    results = {}
    for ids in PRIORITY_SERIES.values():
        for sid in ids:
            print(f"  Fetching {sid}...", file=sys.stderr)
            data = fetch_series(sid)
            if data: results[sid] = data
            time.sleep(0.1)
    md = generate_markdown(results)
    if args.output: Path(args.output).write_text(md); print(f"Saved to {args.output}", file=sys.stderr)
    else: print(md)

if __name__ == "__main__": main()
